<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Boom's blog</title>
        <link rel="stylesheet" type='text/css' href="/vendor/codemirror/theme/dracula.css">
        <link rel="stylesheet" type='text/css' href="/css/all.css">
    </head>
    <body>
        <div id="app">
            <navigation></navigation>
            <router-view></router-view>
            <div class="container">
                <hr />
                <footer class="footer bg-dark text-while">
                    <p>Made in Vietnam since 1992</p>
                </footer>
            </div>
        </div>
        <script src="/js/app.js" type="text/javascript"></script>
    </body>
</html>
