<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Loading...</title>
        <link rel="stylesheet" type='text/css' href="/vendor/codemirror/theme/dracula.css">
        <link rel="stylesheet" type='text/css' href="/css/all.css">
    </head>
    <body>
        <div id="app">
            <navigation></navigation>
            <router-view></router-view>
        </div>
        <script src="/js/app.js" type="text/javascript"></script>
    </body>
</html>
